### ISSUE TITLE
Responsive Styles

### ISSUE THREAD

**Issue by olliejudge** [ganeshnrao/fountainer#1]
Might just be my naivety towards CSS, but is there a straightforward route to making the HTML template responsive? The ch widths make the markup tricky to embed on current pages on a website.

**Comment by ganeshnrao** [comment]
Currently there isn't a way to make it responsive as I designed this for the HTML page to live by itself (not embedding), but I think allowing some way to embed on other pages is the next thing on my list. Can you please share your exact use-case if you don't mind?

**Comment by olliejudge** [comment]
Thanks for the reply. So I've been looking for a way to embed sections of Fountain into a blog in a similar fashion to the legacy plugin [Scrippets](https://fountain.io/scrippets).

My current set up is a Ghost blog that I'd like to drop fountain into, which allows for you to drop raw HTML into a post. I managed to get the current HTML running well by just moving the styles onto the container itself, which looked fine, aside from the fixed width. 

Image attached, let me know if I can offer more details.

<img width="1330" alt="Screenshot 2021-05-13 at 17 31 35" src="https://user-images.githubusercontent.com/9075714/118156414-3dd8e380-b411-11eb-976d-9bcfa925665b.png">

**Comment by ganeshnrao** [comment]
Thanks for the screenshot, that's helpful. So how about this: if we nest all the fountainer specific css within a top level `.fountainer` class, then you could just set some properties on the top level `.fountainer` element (such as [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale())?) which would then make everything inside it relative to the `.fountainer` element. Does that make sense?

**Comment by olliejudge** [comment]
Yes, that feels like it should clear it up. For mobile layout would you just set a different scale at mobile breakpoint?

**Comment by ganeshnrao** [comment]
Yeah, you could use a [media query](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) to set the scales for different device sizes. One tricky thing about the scale css property is that it can probably slow down the page rendering a bit if the screenplay is very long, like thousands of lines long, as scaling will require more processing on the device. Does this seem like a concern?

**Comment by olliejudge** [comment]
Should be fine, I'll only be posting 10-15 pages so shouldn't be too taxing.

**Comment by ganeshnrao** [comment]
Hey, I created a separate repository for browser specific fountainer. You can customize styles and make it responsive with a flag. Take a look https://github.com/ganeshnrao/fountainer-browser

**Comment by olliejudge** [comment]
Oh amazing thanks for putting the work in to create this! Very helpful.
